# Generated by Django 3.1.7 on 2021-03-01 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('rating', models.FloatField(default='', max_length=70)),
                ('price', models.FloatField(default='', max_length=200)),
                ('discount', models.FloatField(default=False)),
                ('brand', models.CharField(default='', max_length=70)),
                ('color', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
